spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/my_game
    username: root
    password: Dd4124894
  mvc:
#    static-path-pattern: /static/**
    async:
      request-timeout: -1
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml
server:
  port: 6660
#  servlet:
#    session:
#      cookie:
#        http-only: false